const ERROR_CODES = {
    UNAUTHORIZED: 401,
    PAGE_NOT_FOUND: 404,
    SERVER_ERROR: 500,
    POST_NOT_EXIST: 800,
    CATEGORY_NOT_EXIST: 801,
    CATEGORY_INVISIBLE: 802
};

module.exports = ERROR_CODES;
