/**
 * 错误码
 * @author fuyun
 * @since 3.0.0
 */
const ERROR_CODES = {
    UNAUTHORIZED: 401,
    PAGE_NOT_FOUND: 404,
    SERVER_ERROR: 500,
    POST_NOT_EXIST: 800,
    POST_SAVE_ERROR: 801,
    POST_COMMENT_CLOSED: 802,
    CATEGORY_NOT_EXIST: 820,
    CATEGORY_INVISIBLE: 821,
    CATEGORY_QUERY_ERROR: 822,
    UPLOAD_ERROR: 840,
    LINK_SAVE_ERROR: 850,
    LINK_REMOVE_ERROR: 851
};

module.exports = ERROR_CODES;
